// This file centralizes the definition of all available tools, organized by category.
const B = import.meta.env.BASE_URL;

export type Pillar = 'documents' | 'images' | 'video';

export interface Tool {
  href: string;
  name: string;
  icon: string;
  subtitle: string;
  pillar: Pillar;
  keywords?: string[];
}

export interface Category {
  name: string;
  tools: Tool[];
}

export const categories: Category[] = [
  {
    name: 'PDF Essentials',
    tools: [
      {
        href: B + 'pdf-multi-tool.html',
        name: 'PDF Multi Tool',
        icon: 'ph-pencil-ruler',
        subtitle:
          'Merge, Split, Organize, Delete, Rotate, Extract and Duplicate in one interface.',
        pillar: 'documents',
        keywords: ['multiple', 'all', 'everything', 'swiss army knife'],
      },
      {
        href: B + 'merge-pdf.html',
        name: 'Merge PDF',
        icon: 'ph-browsers',
        subtitle: 'Combine multiple PDFs into one file.',
        pillar: 'documents',
      },
      {
        href: B + 'split-pdf.html',
        name: 'Split PDF',
        icon: 'ph-scissors',
        subtitle: 'Extract a range of pages into a new PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'compress-pdf.html',
        name: 'Compress PDF',
        icon: 'ph-lightning',
        subtitle: 'Reduce the file size of your PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'edit-pdf.html',
        name: 'PDF Editor',
        icon: 'ph-pencil-simple',
        subtitle: 'Annotate, highlight, redact, comment, and add shapes.',
        pillar: 'documents',
        keywords: [
          'edit',
          'annotate',
          'draw',
          'markup',
          'highlight',
          'redact',
          'comment',
          'shapes',
          'edit-banana',
          'nano-banana',
        ],
      },
      {
        href: B + 'ocr-pdf.html',
        name: 'OCR PDF',
        icon: 'ph-barcode',
        subtitle: 'Make scanned PDFs searchable and copyable.',
        pillar: 'documents',
      },
      {
        href: B + 'compare-pdfs.html',
        name: 'Compare PDFs',
        icon: 'ph-git-diff',
        subtitle: 'Compare two PDFs side by side to find differences.',
        pillar: 'documents',
      },
      {
        href: B + 'flatten-pdf.html',
        name: 'Flatten PDF',
        icon: 'ph-stack-minus',
        subtitle: 'Flatten form fields, annotations, and layers.',
        pillar: 'documents',
      },
      {
        href: B + 'prepare-pdf-for-ai.html',
        name: 'Prepare PDF for AI',
        icon: 'ph-robot',
        subtitle: 'Optimize PDFs for AI ingestion and analysis.',
        pillar: 'documents',
      },
    ],
  },
  {
    name: 'Image & Media Tools',
    tools: [
      {
        href: B + 'edit-banana.html',
        name: 'Edit Banana',
        icon: 'ph-sparkle',
        subtitle:
          'Edit any image with a natural-language prompt — remove, replace, restyle, restore.',
        pillar: 'images',
        keywords: [
          'edit-banana',
          'edit banana',
          'nano-banana',
          'nano banana',
          'gemini',
          'ai image editor',
          'magic edit',
          'prompt edit',
          'image edit',
          'inpaint',
          'restore',
          'restyle',
          'remove person',
        ],
      },
      {
        href: B + 'remove-bg.html',
        name: 'Remove Background',
        icon: 'ph-magic-wand',
        subtitle: 'Instantly remove backgrounds from images using AI.',
        pillar: 'images',
        keywords: [
          'transparent',
          'cutout',
          'bg',
          'erase',
          'photo',
          'rembg',
          'erase background',
        ],
      },
      {
        href: B + 'video-rebrander.html',
        name: 'Video Logo Remover',
        icon: 'ph-video',
        subtitle: 'Remove watermarks and rebrand videos with your logo.',
        pillar: 'video',
        keywords: [
          'mp4',
          'movie',
          'clean',
          'erase',
          'watermark',
          'rebrand',
          'notebooklm',
          'notebook lm',
          'remove logo',
          'inpaint',
        ],
      },
      {
        href: B + 'video-downloader.html',
        name: 'Video Downloader',
        icon: 'ph-download-simple',
        subtitle:
          'Download YouTube or Instagram videos as MP4 or extract MP3 audio.',
        pillar: 'video',
        keywords: ['youtube', 'instagram', 'reel', 'mp4', 'mp3', 'audio', 'download'],
      },
      {
        href: B + 'remove-image-watermark.html',
        name: 'Image Watermark Remover',
        icon: 'ph-image',
        subtitle: 'Remove watermarks from images (JPG, PNG).',
        pillar: 'images',
        keywords: [
          'clean',
          'photo',
          'picture',
          'erase',
          'logo',
          'remove stamp',
          'watermark',
        ],
      },
      {
        href: B + 'remove-watermark.html',
        name: 'PDF Watermark Remover',
        icon: 'ph-eraser',
        subtitle:
          'Remove watermarks from PDFs with AI inpainting (optimized for NotebookLM).',
        pillar: 'documents',
        keywords: [
          'clean',
          'document',
          'erase',
          'logo',
          'remove',
          'watermark',
          'notebooklm',
          'notebook lm',
          'clean pdf',
          'remove stamp',
          'inpaint',
          'ai',
          'smart removal',
        ],
      },
      {
        href: B + 'replace-logo.html',
        name: 'Replace Logo',
        icon: 'ph-repeat',
        subtitle: 'Replace any logo or watermark in an image with your own.',
        pillar: 'images',
        keywords: [
          'logo',
          'brand',
          'swap',
          'notebooklm',
          'notebook lm',
          'lakeb2b',
          'rebrand',
        ],
      },
      {
        href: B + 'image-to-pdf.html',
        name: 'Images to PDF',
        icon: 'ph-images',
        subtitle: 'Convert JPG, PNG, WebP, SVG, and more to PDF.',
        pillar: 'images',
        keywords: ['convert', 'photo', 'picture', 'jpg', 'jpeg', 'png'],
      },
      {
        href: B + 'pdf-to-jpg.html',
        name: 'PDF to JPG',
        icon: 'ph-file-image',
        subtitle: 'Convert PDF pages into JPG images.',
        pillar: 'images',
        keywords: ['convert', 'image', 'picture', 'jpeg', 'extract'],
      },
      {
        href: B + 'pdf-to-png.html',
        name: 'PDF to PNG',
        icon: 'ph-file-image',
        subtitle: 'Convert PDF pages into high-quality PNG images.',
        pillar: 'images',
        keywords: ['convert', 'image', 'picture', 'extract', 'transparent'],
      },
      {
        href: B + 'extract-images.html',
        name: 'Extract Images',
        icon: 'ph-download-simple',
        subtitle: 'Extract all embedded images from your PDF.',
        pillar: 'images',
      },
      {
        href: B + 'pdf-to-svg.html',
        name: 'PDF to SVG',
        icon: 'ph-vector-two',
        subtitle: 'Convert PDF pages to scalable vector graphics.',
        pillar: 'images',
      },
      {
        href: B + 'pdf-to-webp.html',
        name: 'PDF to WebP',
        icon: 'ph-file-image',
        subtitle: 'Convert PDF pages to WebP for web optimization.',
        pillar: 'images',
      },
      {
        href: B + 'pdf-to-tiff.html',
        name: 'PDF to TIFF',
        icon: 'ph-file-image',
        subtitle: 'Convert PDF pages to TIFF images.',
        pillar: 'images',
      },
      {
        href: B + 'pdf-to-bmp.html',
        name: 'PDF to BMP',
        icon: 'ph-file-image',
        subtitle: 'Convert PDF pages to BMP images.',
        pillar: 'images',
      },
      {
        href: B + 'invert-colors.html',
        name: 'Invert Colors',
        icon: 'ph-circle-half',
        subtitle: 'Invert the colors of your PDF for dark mode.',
        pillar: 'documents',
      },
      {
        href: B + 'pdf-to-greyscale.html',
        name: 'PDF to Greyscale',
        icon: 'ph-drop-half-bottom',
        subtitle: 'Convert your PDF to greyscale.',
        pillar: 'documents',
      },
    ],
  },
  {
    name: 'Document Converters',
    tools: [
      {
        href: B + 'word-to-pdf.html',
        name: 'Word to PDF',
        icon: 'ph-microsoft-word-logo',
        subtitle: 'Convert DOCX, DOC to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'excel-to-pdf.html',
        name: 'Excel to PDF',
        icon: 'ph-microsoft-excel-logo',
        subtitle: 'Convert XLSX, XLS to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'powerpoint-to-pdf.html',
        name: 'PowerPoint to PDF',
        icon: 'ph-microsoft-powerpoint-logo',
        subtitle: 'Convert PPTX, PPT to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'pdf-to-docx.html',
        name: 'PDF to Word',
        icon: 'ph-microsoft-word-logo',
        subtitle: 'Convert PDF to editable Word document.',
        pillar: 'documents',
      },
      {
        href: B + 'pdf-to-pptx.html',
        name: 'PDF to PowerPoint',
        icon: 'ph-microsoft-powerpoint-logo',
        subtitle: 'Convert PDF pages to PowerPoint slides.',
        pillar: 'documents',
      },
      {
        href: B + 'pdf-to-excel.html',
        name: 'PDF to Excel',
        icon: 'ph-microsoft-excel-logo',
        subtitle: 'Extract tables from PDF to Excel spreadsheet.',
        pillar: 'documents',
      },
      {
        href: B + 'csv-to-pdf.html',
        name: 'CSV to PDF',
        icon: 'ph-table',
        subtitle: 'Convert CSV spreadsheets to formatted PDF tables.',
        pillar: 'documents',
      },
      {
        href: B + 'pdf-to-csv.html',
        name: 'PDF to CSV',
        icon: 'ph-table',
        subtitle: 'Extract tabular data from PDF to CSV format.',
        pillar: 'documents',
      },
      {
        href: B + 'markdown-to-pdf.html',
        name: 'Markdown to PDF',
        icon: 'ph-markdown-logo',
        subtitle: 'Convert Markdown to nicely formatted PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'pdf-to-markdown.html',
        name: 'PDF to Markdown',
        icon: 'ph-markdown-logo',
        subtitle: 'Convert PDF content to Markdown format.',
        pillar: 'documents',
      },
      {
        href: B + 'text-to-pdf.html',
        name: 'Text to PDF',
        icon: 'ph-text-t',
        subtitle: 'Convert plain text to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'pdf-to-text.html',
        name: 'PDF to Text',
        icon: 'ph-text-aa',
        subtitle: 'Extract text content from PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'email-to-pdf.html',
        name: 'Email to PDF',
        icon: 'ph-envelope',
        subtitle: 'Convert EML and MSG email files to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'json-to-pdf.html',
        name: 'JSON to PDF',
        icon: 'ph-brackets-curly',
        subtitle: 'Convert JSON data to formatted PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'pdf-to-json.html',
        name: 'PDF to JSON',
        icon: 'ph-brackets-curly',
        subtitle: 'Extract structured data from PDF to JSON.',
        pillar: 'documents',
      },
      {
        href: B + 'epub-to-pdf.html',
        name: 'EPUB to PDF',
        icon: 'ph-book-open-text',
        subtitle: 'Convert EPUB e-books to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'pdf-to-pdfa.html',
        name: 'PDF to PDF/A',
        icon: 'ph-archive',
        subtitle: 'Convert PDF to archival PDF/A format.',
        pillar: 'documents',
      },
    ],
  },
  {
    name: 'Image to PDF Converters',
    tools: [
      {
        href: B + 'jpg-to-pdf.html',
        name: 'JPG to PDF',
        icon: 'ph-file-jpg',
        subtitle: 'Convert JPG images to PDF.',
        pillar: 'images',
      },
      {
        href: B + 'png-to-pdf.html',
        name: 'PNG to PDF',
        icon: 'ph-file-png',
        subtitle: 'Convert PNG images to PDF.',
        pillar: 'images',
      },
      {
        href: B + 'svg-to-pdf.html',
        name: 'SVG to PDF',
        icon: 'ph-vector-two',
        subtitle: 'Convert SVG vector graphics to PDF.',
        pillar: 'images',
      },
      {
        href: B + 'webp-to-pdf.html',
        name: 'WebP to PDF',
        icon: 'ph-file-image',
        subtitle: 'Convert WebP images to PDF.',
        pillar: 'images',
      },
      {
        href: B + 'bmp-to-pdf.html',
        name: 'BMP to PDF',
        icon: 'ph-file-image',
        subtitle: 'Convert BMP images to PDF.',
        pillar: 'images',
      },
      {
        href: B + 'tiff-to-pdf.html',
        name: 'TIFF to PDF',
        icon: 'ph-file-image',
        subtitle: 'Convert TIFF images to PDF.',
        pillar: 'images',
      },
      {
        href: B + 'heic-to-pdf.html',
        name: 'HEIC to PDF',
        icon: 'ph-device-mobile',
        subtitle: 'Convert iPhone HEIC photos to PDF.',
        pillar: 'images',
      },
      {
        href: B + 'psd-to-pdf.html',
        name: 'PSD to PDF',
        icon: 'ph-paint-brush',
        subtitle: 'Convert Photoshop PSD files to PDF.',
        pillar: 'images',
      },
      {
        href: B + 'cbz-to-pdf.html',
        name: 'CBZ to PDF',
        icon: 'ph-book',
        subtitle: 'Convert comic book archives to PDF.',
        pillar: 'images',
      },
    ],
  },
  {
    name: 'Office to PDF Converters',
    tools: [
      {
        href: B + 'odt-to-pdf.html',
        name: 'ODT to PDF',
        icon: 'ph-file-doc',
        subtitle: 'Convert OpenDocument text files to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'ods-to-pdf.html',
        name: 'ODS to PDF',
        icon: 'ph-file-xls',
        subtitle: 'Convert OpenDocument spreadsheets to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'odp-to-pdf.html',
        name: 'ODP to PDF',
        icon: 'ph-file-ppt',
        subtitle: 'Convert OpenDocument presentations to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'rtf-to-pdf.html',
        name: 'RTF to PDF',
        icon: 'ph-file-doc',
        subtitle: 'Convert Rich Text Format files to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'txt-to-pdf.html',
        name: 'TXT to PDF',
        icon: 'ph-file-text',
        subtitle: 'Convert plain text files to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'xml-to-pdf.html',
        name: 'XML to PDF',
        icon: 'ph-code',
        subtitle: 'Convert XML data to formatted PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'pages-to-pdf.html',
        name: 'Pages to PDF',
        icon: 'ph-file-doc',
        subtitle: 'Convert Apple Pages documents to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'pub-to-pdf.html',
        name: 'Publisher to PDF',
        icon: 'ph-newspaper',
        subtitle: 'Convert Microsoft Publisher files to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'vsd-to-pdf.html',
        name: 'Visio to PDF',
        icon: 'ph-flow-arrow',
        subtitle: 'Convert Microsoft Visio diagrams to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'wps-to-pdf.html',
        name: 'WPS to PDF',
        icon: 'ph-file-doc',
        subtitle: 'Convert WPS Office documents to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'wpd-to-pdf.html',
        name: 'WPD to PDF',
        icon: 'ph-file-doc',
        subtitle: 'Convert WordPerfect documents to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'fb2-to-pdf.html',
        name: 'FB2 to PDF',
        icon: 'ph-book-open-text',
        subtitle: 'Convert FictionBook e-books to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'mobi-to-pdf.html',
        name: 'MOBI to PDF',
        icon: 'ph-book-open-text',
        subtitle: 'Convert Kindle MOBI e-books to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'xps-to-pdf.html',
        name: 'XPS to PDF',
        icon: 'ph-file',
        subtitle: 'Convert XPS documents to PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'odg-to-pdf.html',
        name: 'ODG to PDF',
        icon: 'ph-paint-brush',
        subtitle: 'Convert OpenDocument graphics to PDF.',
        pillar: 'documents',
      },
    ],
  },
  {
    name: 'Organize & Manage',
    tools: [
      {
        href: B + 'organize-pdf.html',
        name: 'Organize PDF',
        icon: 'ph-files',
        subtitle: 'Duplicate, reorder, and delete pages.',
        pillar: 'documents',
      },
      {
        href: B + 'crop-pdf.html',
        name: 'Crop PDF',
        icon: 'ph-crop',
        subtitle: 'Trim the margins of your PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'rotate-pdf.html',
        name: 'Rotate PDF',
        icon: 'ph-arrow-clockwise',
        subtitle: 'Turn pages in 90-degree increments.',
        pillar: 'documents',
      },
      {
        href: B + 'delete-pages.html',
        name: 'Delete Pages',
        icon: 'ph-trash',
        subtitle: 'Remove specific pages from your document.',
        pillar: 'documents',
      },
      {
        href: B + 'extract-pages.html',
        name: 'Extract Pages',
        icon: 'ph-squares-four',
        subtitle: 'Save a selection of pages as new files.',
        pillar: 'documents',
      },
      {
        href: B + 'page-numbers.html',
        name: 'Page Numbers',
        icon: 'ph-list-numbers',
        subtitle: 'Insert page numbers into your document.',
        pillar: 'documents',
      },
      {
        href: B + 'add-watermark.html',
        name: 'Add Watermark',
        icon: 'ph-drop',
        subtitle: 'Stamp text or an image over your PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'header-footer.html',
        name: 'Header & Footer',
        icon: 'ph-paragraph',
        subtitle: 'Add text to the top and bottom of pages.',
        pillar: 'documents',
      },
      {
        href: B + 'bookmark.html',
        name: 'Bookmarks',
        icon: 'ph-bookmark',
        subtitle: 'Add, edit, and manage PDF bookmarks.',
        pillar: 'documents',
      },
      {
        href: B + 'table-of-contents.html',
        name: 'Table of Contents',
        icon: 'ph-list-bullets',
        subtitle: 'Generate a table of contents for your PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'add-blank-page.html',
        name: 'Add Blank Page',
        icon: 'ph-file-plus',
        subtitle: 'Insert blank pages at any position.',
        pillar: 'documents',
      },
      {
        href: B + 'reverse-pages.html',
        name: 'Reverse Pages',
        icon: 'ph-arrow-u-down-left',
        subtitle: 'Reverse the page order of your PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'remove-blank-pages.html',
        name: 'Remove Blank Pages',
        icon: 'ph-file-minus',
        subtitle: 'Detect and remove blank pages automatically.',
        pillar: 'documents',
      },
      {
        href: B + 'divide-pages.html',
        name: 'Divide Pages',
        icon: 'ph-columns',
        subtitle: 'Split double-page scans into separate pages.',
        pillar: 'documents',
      },
      {
        href: B + 'fix-page-size.html',
        name: 'Fix Page Size',
        icon: 'ph-resize',
        subtitle: 'Standardize page dimensions across all pages.',
        pillar: 'documents',
      },
      {
        href: B + 'alternate-merge.html',
        name: 'Alternate Merge',
        icon: 'ph-shuffle',
        subtitle: 'Interleave pages from two PDFs.',
        pillar: 'documents',
      },
      {
        href: B + 'combine-single-page.html',
        name: 'Combine to Single Page',
        icon: 'ph-arrows-merge',
        subtitle: 'Combine all pages into one long page.',
        pillar: 'documents',
      },
      {
        href: B + 'background-color.html',
        name: 'Background Color',
        icon: 'ph-paint-bucket',
        subtitle: 'Change the background color of PDF pages.',
        pillar: 'documents',
      },
      {
        href: B + 'text-color.html',
        name: 'Text Color',
        icon: 'ph-text-a-underline',
        subtitle: 'Change the text color in your PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'page-dimensions.html',
        name: 'Page Dimensions',
        icon: 'ph-ruler',
        subtitle: 'Resize and change the dimensions of PDF pages.',
        pillar: 'documents',
      },
      {
        href: B + 'rotate-custom.html',
        name: 'Custom Rotation',
        icon: 'ph-arrow-bend-double-up-right',
        subtitle: 'Rotate pages by any custom angle.',
        pillar: 'documents',
      },
      {
        href: B + 'posterize-pdf.html',
        name: 'Posterize PDF',
        icon: 'ph-grid-nine',
        subtitle: 'Split PDF pages into poster-sized tiles.',
        pillar: 'documents',
      },
    ],
  },
  {
    name: 'Security & Privacy',
    tools: [
      {
        href: B + 'sign-pdf.html',
        name: 'Sign PDF',
        icon: 'ph-pen-nib',
        subtitle: 'Draw, type, or upload your signature.',
        pillar: 'documents',
      },
      {
        href: B + 'digital-sign-pdf.html',
        name: 'Digital Signature',
        icon: 'ph-certificate',
        subtitle: 'Add a cryptographic digital signature.',
        pillar: 'documents',
      },
      {
        href: B + 'validate-signature-pdf.html',
        name: 'Validate Signature',
        icon: 'ph-seal-check',
        subtitle: 'Verify digital signatures on a PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'encrypt-pdf.html',
        name: 'Encrypt PDF',
        icon: 'ph-lock',
        subtitle: 'Lock your PDF with a password.',
        pillar: 'documents',
      },
      {
        href: B + 'decrypt-pdf.html',
        name: 'Decrypt PDF',
        icon: 'ph-lock-open',
        subtitle: 'Remove password protection from PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'redact-pdf.html',
        name: 'Redact PDF',
        icon: 'ph-eye-slash',
        subtitle: 'Permanently black out sensitive text and images.',
        pillar: 'documents',
      },
      {
        href: B + 'sanitize-pdf.html',
        name: 'Sanitize PDF',
        icon: 'ph-broom',
        subtitle: 'Remove metadata, annotations, and hidden scripts.',
        pillar: 'documents',
      },
      {
        href: B + 'remove-metadata.html',
        name: 'Remove Metadata',
        icon: 'ph-file-x',
        subtitle: 'Strip sensitive hidden data from your PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'change-permissions.html',
        name: 'Change Permissions',
        icon: 'ph-shield-check',
        subtitle: 'Set print, copy, and edit permissions.',
        pillar: 'documents',
      },
      {
        href: B + 'remove-restrictions.html',
        name: 'Remove Restrictions',
        icon: 'ph-shield-slash',
        subtitle: 'Remove editing and printing restrictions.',
        pillar: 'documents',
      },
      {
        href: B + 'remove-annotations.html',
        name: 'Remove Annotations',
        icon: 'ph-note-blank',
        subtitle: 'Strip all annotations and comments.',
        pillar: 'documents',
      },
    ],
  },
  {
    name: 'Forms & Data',
    tools: [
      {
        href: B + 'form-filler.html',
        name: 'Form Filler',
        icon: 'ph-text-indent',
        subtitle: 'Fill out interactive PDF forms.',
        pillar: 'documents',
      },
      {
        href: B + 'form-creator.html',
        name: 'Form Creator',
        icon: 'ph-selection-all',
        subtitle: 'Create fillable PDF forms with fields.',
        pillar: 'documents',
      },
      {
        href: B + 'extract-tables.html',
        name: 'Extract Tables',
        icon: 'ph-table',
        subtitle: 'Extract tabular data from PDF pages.',
        pillar: 'documents',
      },
      {
        href: B + 'add-attachments.html',
        name: 'Add Attachments',
        icon: 'ph-paperclip',
        subtitle: 'Embed files into your PDF as attachments.',
        pillar: 'documents',
      },
      {
        href: B + 'extract-attachments.html',
        name: 'Extract Attachments',
        icon: 'ph-paperclip',
        subtitle: 'Download embedded files from a PDF.',
        pillar: 'documents',
      },
      {
        href: B + 'edit-attachments.html',
        name: 'Edit Attachments',
        icon: 'ph-paperclip',
        subtitle: 'Manage and modify PDF attachments.',
        pillar: 'documents',
      },
      {
        href: B + 'edit-metadata.html',
        name: 'Edit Metadata',
        icon: 'ph-info',
        subtitle: 'Edit title, author, and other PDF properties.',
        pillar: 'documents',
      },
      {
        href: B + 'view-metadata.html',
        name: 'View Metadata',
        icon: 'ph-info',
        subtitle: 'Inspect PDF properties and metadata.',
        pillar: 'documents',
      },
      {
        href: B + 'pdf-layers.html',
        name: 'PDF Layers',
        icon: 'ph-stack',
        subtitle: 'View and manage optional content layers.',
        pillar: 'documents',
      },
      {
        href: B + 'add-stamps.html',
        name: 'Add Stamps',
        icon: 'ph-stamp',
        subtitle: 'Apply stamps like Approved, Draft, or Confidential.',
        pillar: 'documents',
      },
      {
        href: B + 'create-signature.html',
        name: 'Create Signature',
        icon: 'ph-signature',
        subtitle: 'Design a reusable signature image.',
        pillar: 'documents',
      },
      {
        href: B + 'pdf-to-zip.html',
        name: 'PDF to ZIP',
        icon: 'ph-file-zip',
        subtitle: 'Package PDFs and their assets into a ZIP.',
        pillar: 'documents',
      },
    ],
  },
  {
    name: 'Optimize & Repair',
    tools: [
      {
        href: B + 'repair-pdf.html',
        name: 'Repair PDF',
        icon: 'ph-wrench',
        subtitle: 'Recover data from corrupted PDFs.',
        pillar: 'documents',
      },
      {
        href: B + 'linearize-pdf.html',
        name: 'Linearize PDF',
        icon: 'ph-gauge',
        subtitle: 'Optimize PDF for fast web viewing.',
        pillar: 'documents',
      },
      {
        href: B + 'deskew-pdf.html',
        name: 'Deskew PDF',
        icon: 'ph-perspective',
        subtitle: 'Straighten tilted scanned pages.',
        pillar: 'documents',
      },
      {
        href: B + 'font-to-outline.html',
        name: 'Font to Outline',
        icon: 'ph-text-outdent',
        subtitle: 'Convert fonts to vector outlines for print.',
        pillar: 'documents',
      },
      {
        href: B + 'pdf-booklet.html',
        name: 'PDF Booklet',
        icon: 'ph-book-open',
        subtitle: 'Rearrange pages for booklet printing.',
        pillar: 'documents',
      },
      {
        href: B + 'n-up-pdf.html',
        name: 'N-Up PDF',
        icon: 'ph-squares-four',
        subtitle: 'Arrange multiple pages onto one sheet.',
        pillar: 'documents',
      },
      {
        href: B + 'rasterize-pdf.html',
        name: 'Rasterize PDF',
        icon: 'ph-grid-four',
        subtitle: 'Convert vector content to raster images.',
        pillar: 'documents',
      },
    ],
  },
];

export function toolsByPillar(pillar: Pillar): Tool[] {
  return categories.flatMap((c) => c.tools).filter((t) => t.pillar === pillar);
}

export function topToolsForPillar(pillar: Pillar, n: number): Tool[] {
  return toolsByPillar(pillar).slice(0, n);
}
