// This file centralizes the definition of all available tools, organized by category.
// Each tool can have an optional `tags` array for improved search discoverability.
export interface Tool {
  href: string;
  name: string;
  icon: string;
  subtitle: string;
  tags?: string[];
}

export interface Category {
  name: string;
  tools: Tool[];
}

export const categories: Category[] = [
  {
    name: 'PDF Essentials',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'pdf-multi-tool.html',
        name: 'PDF Multi Tool',
        icon: 'ph-pencil-ruler',
        subtitle:
          'Merge, Split, Organize, Delete, Rotate, Extract and Duplicate in one interface.',
        tags: ['all-in-one', 'multi', 'combine', 'reorder', 'manage'],
      },
      {
        href: import.meta.env.BASE_URL + 'merge-pdf.html',
        name: 'Merge PDF',
        icon: 'ph-browsers',
        subtitle: 'Combine multiple PDFs into one file.',
        tags: ['combine', 'join', 'concatenate', 'append'],
      },
      {
        href: import.meta.env.BASE_URL + 'split-pdf.html',
        name: 'Split PDF',
        icon: 'ph-scissors',
        subtitle: 'Extract a range of pages into a new PDF.',
        tags: ['separate', 'divide', 'cut', 'break'],
      },
      {
        href: import.meta.env.BASE_URL + 'compress-pdf.html',
        name: 'Compress PDF',
        icon: 'ph-lightning',
        subtitle: 'Reduce the file size of your PDF.',
        tags: ['shrink', 'reduce', 'optimize', 'smaller', 'size'],
      },
      {
        href: import.meta.env.BASE_URL + 'edit-pdf.html',
        name: 'PDF Editor',
        icon: 'ph-pencil-simple',
        subtitle: 'Annotate, highlight, redact, comment, and add shapes.',
        tags: [
          'edit',
          'annotate',
          'draw',
          'markup',
          'highlight',
          'redact',
          'comment',
          'shapes',
          'edit-banana',
        ],
      },
      {
        href: import.meta.env.BASE_URL + 'ocr-pdf.html',
        name: 'OCR PDF',
        icon: 'ph-barcode',
        subtitle: 'Make scanned PDFs searchable and copyable.',
        tags: ['scan', 'recognize', 'text recognition', 'optical character'],
      },
    ],
  },
  {
    name: 'Image & Media Tools',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'remove-bg.html',
        name: 'Remove Background',
        icon: 'ph-magic-wand',
        subtitle: 'Instantly remove backgrounds from images.',
        tags: [
          'background',
          'transparent',
          'cutout',
          'rembg',
          'erase background',
        ],
      },
      {
        href: import.meta.env.BASE_URL + 'video-rebrander.html',
        name: 'Video Logo Remover',
        icon: 'ph-video',
        subtitle: 'Remove watermarks and rebrand videos.',
        tags: [
          'video',
          'watermark',
          'logo',
          'rebrand',
          'notebooklm',
          'notebook lm',
          'inpaint',
          'remove logo',
        ],
      },
      {
        href: import.meta.env.BASE_URL + 'remove-image-watermark.html',
        name: 'Image Watermark Remover',
        icon: 'ph-image',
        subtitle: 'Remove watermarks from images (JPG, PNG).',
        tags: ['image', 'watermark', 'clean', 'photo', 'remove stamp'],
      },
      {
        href: import.meta.env.BASE_URL + 'remove-watermark.html',
        name: 'Remove Watermark',
        icon: 'ph-eraser',
        subtitle: 'Remove watermarks with AI-powered smooth inpainting.',
        tags: ['watermark', 'inpaint', 'clean', 'ai', 'smart removal'],
      },
      {
        href: import.meta.env.BASE_URL + 'replace-logo.html',
        name: 'Replace Logo',
        icon: 'ph-repeat',
        subtitle: 'Replace NotebookLM logo with Lake B2B or custom logo.',
        tags: [
          'logo',
          'brand',
          'swap',
          'notebooklm',
          'notebook lm',
          'lakeb2b',
          'rebrand',
        ],
      },
      {
        href: import.meta.env.BASE_URL + 'extract-pages.html',
        name: 'Extract Pages',
        icon: 'ph-squares-four',
        subtitle: 'Save a selection of pages as new files.',
        tags: ['extract', 'pages', 'save', 'selection', 'separate'],
      },
      {
        href: import.meta.env.BASE_URL + 'remove-watermark.html',
        name: 'PDF Watermark Remover',
        icon: 'ph-file-x',
        subtitle: 'Remove watermarks from PDFs (Optimized for Notebook LM).',
        tags: [
          'pdf',
          'watermark',
          'notebooklm',
          'notebook lm',
          'clean pdf',
          'remove stamp',
        ],
      },
      {
        href: import.meta.env.BASE_URL + 'image-to-pdf.html',
        name: 'Images to PDF',
        icon: 'ph-images',
        subtitle: 'Convert JPG, PNG, WebP, SVG, and more to PDF.',
        tags: ['image', 'convert', 'jpg', 'png', 'webp', 'svg', 'photo to pdf'],
      },
      {
        href: import.meta.env.BASE_URL + 'pdf-to-jpg.html',
        name: 'PDF to JPG',
        icon: 'ph-file-image',
        subtitle: 'Convert PDF pages into JPG images.',
        tags: ['convert', 'image', 'jpeg', 'export', 'picture'],
      },
      {
        href: import.meta.env.BASE_URL + 'pdf-to-png.html',
        name: 'PDF to PNG',
        icon: 'ph-file-image',
        subtitle: 'Convert PDF pages into PNG images.',
        tags: ['convert', 'image', 'transparent', 'export', 'picture'],
      },
      {
        href: import.meta.env.BASE_URL + 'extract-images.html',
        name: 'Extract Images',
        icon: 'ph-download-simple',
        subtitle: 'Extract all embedded images from your PDF.',
        tags: ['extract', 'images', 'embedded', 'pull', 'save images'],
      },
    ],
  },
  {
    name: 'Organize & Manage',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'organize-pdf.html',
        name: 'Organize PDF',
        icon: 'ph-files',
        subtitle: 'Duplicate, reorder, and delete pages.',
        tags: ['organize', 'reorder', 'duplicate', 'arrange', 'sort'],
      },
      {
        href: import.meta.env.BASE_URL + 'crop-pdf.html',
        name: 'Crop PDF',
        icon: 'ph-crop',
        subtitle: 'Trim the margins of your PDF.',
        tags: ['crop', 'trim', 'margins', 'resize', 'cut'],
      },
      {
        href: import.meta.env.BASE_URL + 'rotate-pdf.html',
        name: 'Rotate PDF',
        icon: 'ph-arrow-clockwise',
        subtitle: 'Turn pages in 90-degree increments.',
        tags: [
          'rotate',
          'turn',
          'flip',
          'orientation',
          'landscape',
          'portrait',
        ],
      },
      {
        href: import.meta.env.BASE_URL + 'delete-pages.html',
        name: 'Delete Pages',
        icon: 'ph-trash',
        subtitle: 'Remove specific pages from your document.',
        tags: ['delete', 'remove', 'pages', 'discard'],
      },
      {
        href: import.meta.env.BASE_URL + 'page-numbers.html',
        name: 'Page Numbers',
        icon: 'ph-list-numbers',
        subtitle: 'Insert page numbers into your document.',
        tags: ['page numbers', 'numbering', 'pagination', 'footer'],
      },
      {
        href: import.meta.env.BASE_URL + 'add-watermark.html',
        name: 'Add Watermark',
        icon: 'ph-drop',
        subtitle: 'Stamp text or an image over your PDF.',
        tags: ['watermark', 'stamp', 'overlay', 'brand', 'text overlay'],
      },
      {
        href: import.meta.env.BASE_URL + 'remove-watermark.html',
        name: 'Remove Watermark',
        icon: 'ph-eraser',
        subtitle: 'Remove watermarks with AI-powered smooth inpainting.',
        tags: ['watermark', 'inpaint', 'clean', 'ai', 'smart removal'],
      },
      {
        href: import.meta.env.BASE_URL + 'replace-logo.html',
        name: 'Replace Logo',
        icon: 'ph-repeat',
        subtitle: 'Replace NotebookLM logo with Lake B2B or custom logo.',
        tags: [
          'logo',
          'brand',
          'swap',
          'notebooklm',
          'notebook lm',
          'lakeb2b',
          'rebrand',
        ],
      },
      {
        href: import.meta.env.BASE_URL + 'header-footer.html',
        name: 'Header & Footer',
        icon: 'ph-paragraph',
        subtitle: 'Add text to the top and bottom of pages.',
        tags: ['header', 'footer', 'top', 'bottom', 'text'],
      },
    ],
  },
  {
    name: 'Security & Privacy',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'sign-pdf.html',
        name: 'Sign PDF',
        icon: 'ph-pen-nib',
        subtitle: 'Draw, type, or upload your signature.',
        tags: ['sign', 'signature', 'draw', 'write', 'autograph', 'e-sign'],
      },
      {
        href: import.meta.env.BASE_URL + 'encrypt-pdf.html',
        name: 'Encrypt PDF',
        icon: 'ph-lock',
        subtitle: 'Lock your PDF with a password.',
        tags: ['encrypt', 'password', 'protect', 'lock', 'secure'],
      },
      {
        href: import.meta.env.BASE_URL + 'decrypt-pdf.html',
        name: 'Decrypt PDF',
        icon: 'ph-lock-open',
        subtitle: 'Remove password protection from PDF.',
        tags: ['decrypt', 'unlock', 'remove password', 'unprotect'],
      },
      {
        href: import.meta.env.BASE_URL + 'sanitize-pdf.html',
        name: 'Sanitize PDF',
        icon: 'ph-broom',
        subtitle: 'Remove metadata, annotations, and hidden scripts.',
        tags: [
          'sanitize',
          'clean',
          'strip',
          'remove metadata',
          'privacy',
          'safe',
        ],
      },
      {
        href: import.meta.env.BASE_URL + 'remove-metadata.html',
        name: 'Remove Metadata',
        icon: 'ph-file-x',
        subtitle: 'Strip sensitive hidden data.',
        tags: [
          'metadata',
          'exif',
          'properties',
          'hidden data',
          'privacy',
          'strip',
        ],
      },
      {
        href: import.meta.env.BASE_URL + 'digital-sign-pdf.html',
        name: 'Digital Signature',
        icon: 'ph-certificate',
        subtitle: 'Add a cryptographic digital signature.',
        tags: ['digital', 'certificate', 'crypto', 'verify', 'pkcs', 'x509'],
      },
    ],
  },
  {
    name: 'Document Converters',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'word-to-pdf.html',
        name: 'Word to PDF',
        icon: 'ph-microsoft-word-logo',
        subtitle: 'Convert DOCX, DOC to PDF.',
        tags: ['word', 'docx', 'doc', 'convert', 'microsoft', 'office'],
      },
      {
        href: import.meta.env.BASE_URL + 'excel-to-pdf.html',
        name: 'Excel to PDF',
        icon: 'ph-microsoft-excel-logo',
        subtitle: 'Convert XLSX, XLS to PDF.',
        tags: ['excel', 'xlsx', 'xls', 'spreadsheet', 'convert', 'microsoft'],
      },
      {
        href: import.meta.env.BASE_URL + 'powerpoint-to-pdf.html',
        name: 'PowerPoint to PDF',
        icon: 'ph-microsoft-powerpoint-logo',
        subtitle: 'Convert PPTX, PPT to PDF.',
        tags: [
          'powerpoint',
          'pptx',
          'ppt',
          'slides',
          'presentation',
          'convert',
        ],
      },
      {
        href: import.meta.env.BASE_URL + 'pdf-to-docx.html',
        name: 'PDF to Word',
        icon: 'ph-microsoft-word-logo',
        subtitle: 'Convert PDF to editable Word doc.',
        tags: ['word', 'docx', 'convert', 'editable', 'microsoft'],
      },
      {
        href: import.meta.env.BASE_URL + 'pdf-to-pptx.html',
        name: 'PDF to PowerPoint',
        icon: 'ph-microsoft-powerpoint-logo',
        subtitle: 'Convert PDF to PowerPoint slides.',
        tags: ['powerpoint', 'pptx', 'slides', 'presentation', 'convert'],
      },
      {
        href: import.meta.env.BASE_URL + 'markdown-to-pdf.html',
        name: 'Markdown to PDF',
        icon: 'ph-markdown-logo',
        subtitle: 'Convert Markdown to nicely formatted PDF.',
        tags: ['markdown', 'md', 'convert', 'format', 'github'],
      },
      {
        href: import.meta.env.BASE_URL + 'text-to-pdf.html',
        name: 'Text to PDF',
        icon: 'ph-text-t',
        subtitle: 'Convert plain text to PDF.',
        tags: ['text', 'txt', 'plain text', 'convert'],
      },
      {
        href: import.meta.env.BASE_URL + 'pdf-to-text.html',
        name: 'PDF to Text',
        icon: 'ph-text-aa',
        subtitle: 'Extract text from PDF.',
        tags: ['text', 'extract', 'copy', 'txt', 'plain text'],
      },
    ],
  },
  {
    name: 'Optimize & Repair',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'repair-pdf.html',
        name: 'Repair PDF',
        icon: 'ph-wrench',
        subtitle: 'Recover data from corrupted PDFs.',
        tags: ['repair', 'fix', 'corrupt', 'broken', 'recover', 'damaged'],
      },
      {
        href: import.meta.env.BASE_URL + 'linearize-pdf.html',
        name: 'Linearize PDF',
        icon: 'ph-gauge',
        subtitle: 'Optimize PDF for fast web viewing.',
        tags: ['linearize', 'optimize', 'web', 'fast', 'streaming'],
      },
      {
        href: import.meta.env.BASE_URL + 'deskew-pdf.html',
        name: 'Deskew PDF',
        icon: 'ph-perspective',
        subtitle: 'Straighten tilted scanned pages.',
        tags: ['deskew', 'straighten', 'tilt', 'scan', 'align', 'level'],
      },
      {
        href: import.meta.env.BASE_URL + 'font-to-outline.html',
        name: 'Font to Outline',
        icon: 'ph-text-outdent',
        subtitle: 'Convert fonts to vector outlines.',
        tags: ['font', 'outline', 'vector', 'embed', 'curves', 'print'],
      },
      {
        href: import.meta.env.BASE_URL + 'pdf-booklet.html',
        name: 'PDF Booklet',
        icon: 'ph-book-open',
        subtitle: 'Rearrange pages for booklet printing.',
        tags: ['booklet', 'print', 'fold', 'pamphlet', 'brochure'],
      },
      {
        href: import.meta.env.BASE_URL + 'n-up-pdf.html',
        name: 'N-Up PDF',
        icon: 'ph-squares-four',
        subtitle: 'Arrange multiple pages onto one sheet.',
        tags: [
          'n-up',
          'multiple',
          'pages per sheet',
          'layout',
          'imposition',
          '2-up',
          '4-up',
        ],
      },
    ],
  },
];
